server:
  context-path: /sample
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:D:/tmp/sample
    username: sa
    password: 
  thymeleaf: 
    mode: LEGACYHTML5
    cache: false
# デフォルトBASIC認証の無効化
security:
  basic:
    enabled: false
doma:
  dialect: H2
  naming: SNAKE_LOWER_CASE
